apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: airflow-dbt:local
          command:
            - "bash"
            - "-c"
            - |
              airflow db migrate &&
              airflow users create \
                --username admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com \
                --password admin &&
              airflow webserver
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://dbt:dbt@postgres-dbt:5432/jaffle_shop
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://dbt:dbt@postgres-dbt:5432/jaffle_shop
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /opt/airflow/dags
            - name: _AIRFLOW_WWW_USER_USERNAME  # Ensures the username is set
              value: admin
            - name: _AIRFLOW_WWW_USER_PASSWORD  # Ensures the password is set
              value: admin  
              
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: airflow
