apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-dbt
spec:
  serviceName: postgres-dbt
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dbt
  template:
    metadata:
      labels:
        app: postgres-dbt
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: dbt
            - name: POSTGRES_PASSWORD
              value: dbt
            - name: POSTGRES_DB
              value: jaffle_shop
          ports:
            - containerPort: 5432 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dbt
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-dbt 