default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-dbt
      user: dbt
      password: dbt
      port: 5432
      dbname: jaffle_shop
      schema: public
      threads: 4